### ISSUE TITLE
devzwy的新tflite文件是否兼容

### ISSUE THREAD

**Issue by CensorKo** [davewang/open_nsfw_ios#2]
我看到android版的作者devzwy更新了tflite文件的模型。模型大小改动较大，原量化模型虽小(6M)，但对GPU加速支持不友好，新模型大约23M，完美支持GPU加速并优化识别精度，加速效果明显。

不知道他的nsfw.tflite能否用于本项目。如果不行，有没有升级的计划。非常感谢你的项目。

**Comment by xiaohange** [comment]
tflite通用
